# Generated by Django 4.2.6 on 2023-12-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fats',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='proteins',
            new_name='protein',
        ),
    ]
