# Generated by Django 4.2.6 on 2023-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_rename_fats_food_fat_rename_proteins_food_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
