# Generated by Django 4.2.6 on 2023-12-03 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='consumed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 15, 21, 52, 112944)),
        ),
    ]
