# Generated by Django 4.2.6 on 2023-12-03 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_consume_consumed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='consumed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
