# Generated by Django 4.2.6 on 2023-12-03 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0006_alter_consume_consumed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(on_delete=models.SET('deleted food'), to='counter.food'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('deleted user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
